cache: bundler
rvm:
- 2.2.7
- 2.3.4
- 2.4.1
before_script: 
script: cd ruby && bundle exec rspec
after_success:
- cd ruby && bundle exec codeclimate-test-reporter
env:
  CODECLIMATE_REPO_TOKEN=4858a48c535871340f2ff9985acb163fc36ae4fa622f1f915252d88cb68e66e4
notifications:
  slack:
    secure: QaaD9WpCYoGFITVd8ku3cjkw1ADJ/rqsPgFGsbRxjPOj1HDzkkUVs20IK0AysxeI6CPY31rfWqbBcE4I4dUE49uIhpOoBXZ8GDYunUONeEmqGwrqZtV/8NqMLNc0Ouu5Jp/KVlnMO93Pcg97BBW81t1koxqyvgSU5oEmJdTmQZIsRNprhczeCj7T6jbb12LEA8uKi2qnp+FAhL5NJczHxqWCd2pWThtbA+hiRmH/mU0480n1eRForN51jDYUrgxb4PamhfUUG1xkzMPzGsvJTMCQDOG4eyHaq71vlZ3z9BbQG6vbcjfEQHVwfrPRz1k0luIlxMXJxszCFnnLVqeRYs85y4FOQSrLsDfsyLCU+1NgLqtseN6jNKOtY624Ok7YvYzsVYez/CPWUG1d2NIRMYQ+BoL2VQ3SDfvr4bYQ02QmqlhM1bKqmBoM+WmiH1FQk6CKOFcmlSkgkFilLi6YSB/EisQ5V5jo7DnzD38VVACo6J6SgVk2D6soONE3zev34Qa6PIOuwTTlXl6JKH0cpiG058lI+Oza+0xi0jg58sZG3jxeGM7m4wg66htgyN1oRQjIukSR+IJ3PZlFKTLvx2rCUcYz+8fRpPCMTSIVLeju5oPqOm0VRUni2dG5JGyNACV8EhI4ZMcfl7+uFTIagCnllRftBx8lY6AxWN3WpDE=
addons:
  code_climate:
    repo_token:
      secure: Uqz+72sXWtg4+WyGuWt6avXYVqdkCayfcv/Jn3//ib6+qjA10bLavGHvjOBBoQ7P65F88uWRYsCgacRTgcfS5CXlMIPZch8nm6I05xVoOT5ajmbUqy/ipgXXCqniY+0C5FJJ0p2n1a5iuaGINH5kqMFA3K6J9n9z4bVBqliUfbRws0ufQS726BbH+DmOEC+/8EZntkH4RGLuCXxHO2RlxGpZEEI764cEp4+WnWymCRfSXUgPwzMCxWX43LopQSrpQpPkmBfpZhEa2hw0FEDUdlv1qIuY/YZx/DA0Jcy7Ecl9ixZdoliUlFI0oVq/eIFrTtjSbIpEJtM7y2gisqO90Jb1MrDD9H2kCMIPtIrrGB35a/isTIxeoRD4M4BnOAAqFVMCP5HtJmBKaaUUZrF0kYD14tSrVuS60Ird4anz9OelKv8iGQvIbH7069BVm4LHVN6yUQYqh0lr3u9KFj8xjBtsiB0PEDcRbvthl4NFlLZwzSG6JV1jDjiYCM18LRD5A6g2zOL04sG68Gy97N1OrMpbFrAkbyGTxxj7b+FICLkzT1FKlPOeK/soDDDxOuXjfiOHBe11D2xFUrrERyDqLm06TAGh8pH9e0J+cfNF4U+K8FC8ZjMKciR5OADZ5P1lu2cGmGBPbIlhAHScR2ndUFwGzLEz6vpQzewSJP4rSoI=
